% README
% The electrode256_alignedtoFs is an electrode file
% in there whose coordinates are mapped to the scalp mesh of the Freesurfer
% fsaverage head. 

% fsaverage_labels_connectome contains the Brain surfaces. This means both
% the original brain surface with all ~370000 vertices or so and the down
% sampled one with ~81k vertices that was used to create the lead field
% with the help of openMeeg. It also has the structural connectome at
% several levels of parcellations. This means that we started from the 83
% ROIs of the Desikan-Killiany atlas and they were broken down into 150
% ROis, 258 ROIs, 500 ROIs and 1015 ROIs. The structural connectome at each
% of these scales is in the adj matrices. For each of these scales we need
% to have the labels for the set of vertices that form the Brain surface.
% This exists in both labels_nosubcort for the full brain and in
% allLabels_DS for the downsampled brain at all 5 scales. 
% The ROInames cells contain names for the Regions of interest. All ROI
% labels at smaller scales need to be understood using the ROI labels for
% the largest scale (83 ROIs). 

% fsaverage_leadField is the lead field computed from
% the Brain surface (downsampled so 81k vertices), and the Scalp, Skull and
% CSF boundary meshes that is inside the 'surfaces' folder. 

% the fsaverage_reducedLeadField contains two structures. redLeadField is a
% structure with the vertices for the set of 1015 Rois (really its 998 once
% we exclude 1, and the subcortical ROis which is in subcort). There are
% multiple ways to select the set of vertex that represents an ROI and the
% different ways it could be selected are in redLeadField.
% maxCorr: picks the vertex in an ROI with the maximum sum of absolute correlations to the rest of the vertices projection onto the scalp.
% mean: takes mean of vertices in the ROI. Minimizes euclidean distance between spatial filter created by each vertex at scalp
% shortPathLength: Finds the vertex at the topological center of an ROI - equivalent to taking an ROI spreading it out as a plane in and of itself nad locating center of the plane
% maxCorrMinNeighborCorr: Finds vertex with maximum sum of absolute correlations internal to the ROI AND minimum correlation to the spatial filter generated by neighbor ROIs
% the vertices used in each case is in redLeadFieldVertex.
% labelVerts has the set of vertices that compose each ROI.
% vertexNeighbors has a list of neighbors for each vertex. 
%% Surfaces
% Inside the surfaces folder are the surfaces both in Freesurfer format and
% as mat files.
%% baseFiles
% This contains the files needed to compute an OpenMeeg boundary element
% model of the brain. They are created using the files in the surfaces
% folder. There is also a shell file that runs the necessary commands to
% run Openmeeg to build the lead field.
